[package]
name = "json_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.10", features = ["derive"] }
rand = "0.8"
env_logger = "0.7"
log = "0.4"
